sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

# CODECOV_TOKEN
# Created by running `travis encrypt -r dreal/dreal4 CODECOV_TOKEN="SECURE_TOKEN_VALUE"`
secure: "K4HzcNOd9Kzp5OhHc/bBldhaYLado14f/FT0kCUXYJBfyRt94tDMVhs1fHMwSg1PFqCFrR/DWXpDK4LDUg+fHPUuSBmx7pkrbS8Ou6y+CkeavRefX6TiOsdOseO7I9EOS5Lu5lwFX5Dik7vktLBRsFmubQ4E2kDTIGwCQ8xQzXlsv5nWUNoMTrtoG75p362EpKmLq/2IbdGQ3btQ5vjM3uT+L9CQfWJ6/IrWNzilY4KBciuZSD1PCkQ4AoxjeRH+MnRqu7IpvPEcMHcKzfN7HamIIihaWM8Xf+A2wHVypMN/jr9ONMoHSZzosMzBK38NOTyxaxAqpO0/RO0CrpjGqDjRCpT6cejndeEP4Zr1J2mnjnrsiFVZXJfQRVzvhcWa/1V0b4lK5wjPFeF/l2fwYqkwu+IMGmzVupXJ8s9L7XSZtocLeZ3dYWpUqHDI84zhb3Sts1FSfp7G8a6GshL8Mj8V795YnfVE9Y7WTlpedZ9/6aeUlgaKwbAuq1Bav2PJd435QO4thWi4ODVF9vbNjPm4ocNFQZ6YiEqbvoc2hT6E92Y309DLVGzyTLCmDm3Vkk6VVjhrvttOGXVmHFIcDvgJwvLZQ4nkw46kd8PafaEDoG4KP730qCF9CbE/SllmimTACb9cGkkCZj5O4pQEivlqc5jaoradRxht/0E0KQw="

cache:
  directories:
    - $HOME/.bazel-output-base
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER="--compiler=gcc-7" BUILD_TYPE="-c dbg"
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER="--compiler=gcc-6" BUILD_TYPE="-c dbg"
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER="--compiler=gcc-5" BUILD_TYPE="-c dbg"
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER="--compiler=gcc-4.9" BUILD_TYPE="-c dbg"
    - compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-5.0', 'ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'clang-5.0']
      env:
        - COMPILER="--compiler=clang-5.0" BUILD_TYPE="-c dbg"
    - compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0', 'ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'clang-4.0']
      env:
        - COMPILER="--compiler=clang-4.0" BUILD_TYPE="-c dbg"
    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'clang-3.9']
      env:
        - COMPILER="--compiler=clang-3.9" BUILD_TYPE="-c dbg"
    - compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0', 'ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'clang-4.0']
      env:
        - COMPILER="--compiler=clang-4.0" CONFIG="--config asan"
    - compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0', 'ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'clang-4.0']
      env:
        - COMPILER="--compiler=clang-4.0" CONFIG="--config lsan"
    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'clang-3.9']
      env:
        - COMPILER="--compiler=clang-3.9" BUILD_TYPE="-c dbg"
        - COV="ON" COV_OPTION="--config=kcov"
    - os: osx
      osx_image: xcode8.3  # macOS-10.12
      compiler: clang
      env:
        - COMPILER="" BUILD_TYPE="-c opt"
    - os: osx
      osx_image: xcode9.3beta  # macOS-10.13
      compiler: clang
      env:
        - COMPILER="" BUILD_TYPE="-c opt"

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo add-apt-repository ppa:dreal/dreal -y;
      sudo apt update;
      sudo apt install bison coinor-libclp-dev flex pkg-config libibex-dev libnlopt-dev;
      BAZEL_VERSION=0.11.1;
      wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb;
      sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb;
      BAZEL_LOCAL_RESOURCES=2048,1,1.0;
      TEST_TAG_FILTERS=;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew update;
      brew install bazel pkg-config dreal-deps/ibex/ibex@2.6.5 nlopt || true;
      BAZEL_LOCAL_RESOURCES=2048,2,1.0;
      TEST_TAG_FILTERS=unit;
    fi
  - if [ "${COV}" == "ON" ]; then
      sudo apt install -y binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev;
      git clone https://github.com/SimonKagstrom/kcov --depth 1;
      cd kcov;
      mkdir build;
      cd build;
      cmake ../;
      make -j;
      sudo cp src/kcov /usr/bin/;
      cd ../../;
      TEST_TAG_FILTERS=unit;
    fi

script:
  - |
    bazel \
      --batch \
      --output_base="$HOME/.bazel-output-base" \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --local_resources=${BAZEL_LOCAL_RESOURCES} \
      //...  ${COMPILER} ${BUILD_TYPE} ${CONFIG} \
      ${COV_OPTION} \
      --test_tag_filters=${TEST_TAG_FILTERS}

after_success:
  - if [ "${COV}" == "ON" ]; then
      bash <(curl -s https://codecov.io/bash) -s bazel-kcov -t ${CODECOV_TOKEN};
    fi

notifications:
  recipients:
    - soonho.kong@gmail.com
  email:
    on_success: change
    on_failure: always
