name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  macos_catalina_build_and_test:
    name: macos catalina build and test
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: ./setup/mac/install_prereqs.sh
        shell: zsh -efuo pipefail {0}
      - name: build and test
        run: bazel test //... -c dbg
  ubuntu_focal_build_and_test:
    name: ubuntu-20.04 build and test
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: sudo ./setup/ubuntu/20.04/install_prereqs.sh
        shell: bash
      - name: build and test
        run: bazel test //... -c dbg
  ubuntu_bionic_build_and_test:
    name: ubuntu 18.04 build and test
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: sudo ./setup/ubuntu/18.04/install_prereqs.sh
        shell: bash
      - name: build and test
        run: bazel test //... -c dbg
  ubuntu_trusty_build_and_test:
    name: ubuntu 16.04 build and test
    runs-on: ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: sudo ./setup/ubuntu/16.04/install_prereqs.sh
        shell: bash
      - name: build and test
        run: bazel test //... -c dbg
